version: "3"

tasks:
  default:
    desc: "Список доступных задач"
    cmds:
      - task --list

  gen-all:
    desc: "Геренация go кода для всех proto"
    cmds:
      - protoc -I proto -I third_party/googleapis proto/v1/*/*.proto --go_out=./proto/gen/go/ --go_opt=paths=source_relative --go-grpc_out=./proto/gen/go/ --go-grpc_opt=paths=source_relative

  gen-auth:
    desc: "Генерация go кода для auth"
    cmds:
      - protoc -I proto -I third_party/googleapis proto/v1/auth/*.proto --go_out=./proto/gen/go/ --go_opt=paths=source_relative --go-grpc_out=./proto/gen/go/ --go-grpc_opt=paths=source_relative

  gen-notify:
    desc: "Генерация go кода для notify"
    cmds:
      - protoc -I proto -I third_party/googleapis proto/v1/notify/*.proto --go_out=./proto/gen/go/ --go_opt=paths=source_relative --go-grpc_out=./proto/gen/go/ --go-grpc_opt=paths=source_relative

  gen-menu:
    desc: "Генерация go кода для menu"
    cmds:
      - protoc -I proto -I third_party/googleapis proto/v1/menu/*.proto --go_out=./proto/gen/go/ --go_opt=paths=source_relative --go-grpc_out=./proto/gen/go/ --go-grpc_opt=paths=source_relative

  gen-order:
    desc: "Генерация go кода для order"
    cmds:
      - protoc -I proto -I third_party/googleapis proto/v1/order/*.proto --go_out=./proto/gen/go/ --go_opt=paths=source_relative --go-grpc_out=./proto/gen/go/ --go-grpc_opt=paths=source_relative

  gen-payment:
    desc: "Генерация go кода для payment"
    cmds:
      - protoc -I proto -I third_party/googleapis proto/v1/payment/*.proto --go_out=./proto/gen/go/ --go_opt=paths=source_relative --go-grpc_out=./proto/gen/go/ --go-grpc_opt=paths=source_relative

  gen-user:
    desc: "Генерация go кода для user"
    cmds:
      - protoc -I proto -I third_party/googleapis proto/v1/auth/*.proto --go_out=./proto/gen/go/ --go_opt=paths=source_relative --go-grpc_out=./proto/gen/go/ --go-grpc_opt=paths=source_relative

  gen-gateway-all:
    desc: "Генерация gRPC-Gateway для всех proto"
    cmds:
      - protoc -I proto -I third_party/googleapis proto/v1/*/*.proto --grpc-gateway_out=./proto/gen/go/ --grpc-gateway_opt=paths=source_relative

  gen-gateway-auth:
    desc: "Генерация gRPC-Gateway для auth"
    cmds:
      - protoc -I proto -I third_party/googleapis proto/v1/auth/*.proto --grpc-gateway_out=./proto/gen/go/ --grpc-gateway_opt=paths=source_relative

  gen-gateway-notify:
    desc: "Генерация gRPC-Gateway для notify"
    cmds:
      - protoc -I proto -I third_party/googleapis proto/v1/notify/*.proto --grpc-gateway_out=./proto/gen/go/ --grpc-gateway_opt=paths=source_relative

  gen-gateway-menu:
    desc: "Генерация gRPC-Gateway для menu"
    cmds:
      - protoc -I proto -I third_party/googleapis proto/v1/menu/*.proto --grpc-gateway_out=./proto/gen/go/ --grpc-gateway_opt=paths=source_relative

  gen-gateway-order:
    desc: "Генерация gRPC-Gateway для order"
    cmds:
      - protoc -I proto -I third_party/googleapis proto/v1/order/*.proto --grpc-gateway_out=./proto/gen/go/ --grpc-gateway_opt=paths=source_relative

  gen-gateway-payment:
    desc: "Генерация gRPC-Gateway для payment"
    cmds:
      - protoc -I proto -I third_party/googleapis proto/v1/payment/*.proto --grpc-gateway_out=./proto/gen/go/ --grpc-gateway_opt=paths=source_relative

  gen-gateway-user:
    desc: "Генерация gRPC-Gateway для user"
    cmds:
      - protoc -I proto -I third_party/googleapis proto/v1/user/*.proto --grpc-gateway_out=./proto/gen/go/ --grpc-gateway_opt=paths=source_relative

  gen-swagger-all:
    desc: "Генерация Swagger документации для всех proto"
    cmds:
      - protoc -I proto -I third_party/googleapis proto/v1/*/*.proto --openapiv2_out=./proto/gen/swagger/ --openapiv2_opt=logtostderr=true

  gen-swagger-auth:
    desc: "Генерация Swagger документации для auth"
    cmds:
      - protoc -I proto -I third_party/googleapis proto/v1/auth/*.proto --openapiv2_out=./proto/gen/swagger/ --openapiv2_opt=logtostderr=true

  gen-swagger-notify:
    desc: "Генерация Swagger документации для notify"
    cmds:
      - protoc -I proto -I third_party/googleapis proto/v1/notify/*.proto --openapiv2_out=./proto/gen/swagger/ --openapiv2_opt=logtostderr=true

  gen-swagger-menu:
    desc: "Генерация Swagger документации для menu"
    cmds:
      - protoc -I proto -I third_party/googleapis proto/v1/menu/*.proto --openapiv2_out=./proto/gen/swagger/ --openapiv2_opt=logtostderr=true

  gen-swagger-order:
    desc: "Генерация Swagger документации для order"
    cmds:
      - protoc -I proto -I third_party/googleapis proto/v1/order/*.proto --openapiv2_out=./proto/gen/swagger/ --openapiv2_opt=logtostderr=true

  gen-swagger-payment:
    desc: "Генерация Swagger документации для payment"
    cmds:
      - protoc -I proto -I third_party/googleapis proto/v1/payment/*.proto --openapiv2_out=./proto/gen/swagger/ --openapiv2_opt=logtostderr=true

  gen-swagger-user:
    desc: "Генерация Swagger документации для user"
    cmds:
      - protoc -I proto -I third_party/googleapis proto/v1/user/*.proto --openapiv2_out=./proto/gen/swagger/ --openapiv2_opt=logtostderr=true

  gen-complete:
    desc: "Полная генерация: Go, gRPC, Gateway и Swagger для всех proto"
    cmds:
      - task: gen-all
      - task: gen-gateway-all
      - task: gen-swagger-all
